# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Set environment variables for HTTP transport
ENV USE_HTTP=true
ENV PORT=8081

# Expose port 8081 (Smithery standard)
EXPOSE 8081

# Start the MCP server in HTTP mode
CMD ["npm", "start"]
