# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install dependencies first (better layer caching)
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Set environment variables for HTTP transport
ENV USE_HTTP=true
ENV PORT=8080
ENV NODE_ENV=production

# Expose port 8080 (Smithery standard for HTTP servers)
EXPOSE 8080

# Add healthcheck for container orchestration
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1

# Start the MCP server in HTTP mode
CMD ["node", "build/index.js"]
